### ISSUE TITLE
Butterfly's logo

### ISSUE THREAD

**Issue by Cowa** [Matthieu-Riou/Butterfly#10]
#### Proposition de logo

![butterfly_logo](https://cloud.githubusercontent.com/assets/1422403/5132679/1c469ba6-70ff-11e4-95bc-19d34f2ac84d.png)

@Matthieu-Riou, qu'en penses-tu ? :smile:

**Comment by ojbruce** [comment]
:+1:  magnifique #huhu

**Comment by Cowa** [comment]
:+1: Au moins deux votes sur trois \o/
La majorité gagne :dancers::rabbit:

**Comment by Matthieu-Riou** [comment]
Eh ! Depuis quand on est 3 à pouvoir voter ? 
Sinon, j'aime bien le logo, même si je le trouve un peu vide en haut à droite du coup. (Surtout quand on le voit tout seul sur une page).
Et Chloé aime pas les bords flous du rhino, en contraste avec la netteté du hashtag #histoiredelart

À part ça, je vote pour :+1:

**Comment by Cowa** [comment]
Mini update #gimp #graphist 
![butterfly_logo](https://cloud.githubusercontent.com/assets/1422403/5165970/82a59476-73eb-11e4-802b-9c063f1818f0.png)

**Comment by Matthieu-Riou** [comment]
:+1:
