### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by Matthieu-Riou** [Matthieu-Riou/Butterfly#15]
Voici l'état du programme : 
- Le buffer ne connait rien à part lui même
- L'editor gère un buffer, avec ses curseurs
- L'editorManager manège plusieurs buffers, switch des uns aux autres, gère le clipboard (soon)
- L'interface capture les entrées user, les envoie à l'editorManager, puis met à jour l'affichage du buffer

Sauf que dans le cas d'utilisateurs multiples, le buffer est modifié par un autre utilisateur, mais ne se met pas à jour sur l'interface du premier.

Il faut donc que l'interface se mette à jour pour chaque buffer en direct.
Je conseille un pattern Observer. À voir comment on gère les intermédiaires : est-ce que l'interface observe l'editorManager qui observe l'editor, qui observe le buffer ?

C'est à vous de jouer !

**Comment by Cowa** [comment]
Challenge accepted ! :dancer:

**Comment by Cowa** [comment]
PR associé https://github.com/Matthieu-Riou/Butterfly/pull/19
