### ISSUE TITLE
Action et Historique

### ISSUE THREAD

**Issue by Matthieu-Riou** [Matthieu-Riou/Butterfly#18]
Je suis en train de réfléchir pour gérer les actions, et les macro (méta-actions). Y'aura sûrement un composite là dedans : une action est soit une action de base, soit une composée d'actions.
Mais j'ai du mal sur la conception, c'est un peu flou. Voici donc mes quelques idées : 
Une action est "abstraite" dans le sens où elle n'est pas appliquée directement. On définie d'abord une instance (ex : Insertion de "bonjour" à la position 6), puis on la concrétise en l'appliquant sur un buffer (avec execute() ). Ainsi, on peut réappliquer une action plusieurs fois, sur des buffers différents.
À coté de ses actions abstraites, il y a l'historique. On a là des "actions concètes" qui ont déjà été appliqué sur un buffer donnée, et se sont donc concrétisé (mécanique quantique \o/). Par exemple, pour la Deletion, l'action "abstraite" ne sait pas quel texte sera supprimé. L'action "concrète" de l'historique a été appliquée, et a donc retenu le texte (pour pouvoir l'annuler).

Comme ça, je dirai que l'action "abstraite" et l'action "concrète" sont deux objets différents. Une action "abstraite" est instanciée, puis appliquée sur un buffer. Le buffer va ensuite instancié une action "concrète" pour son historique. 

Qu'en penses tu ?

**Comment by Cowa** [comment]
Du coup, ça ressemblerait à ça ?
![untitled diagram](https://cloud.githubusercontent.com/assets/1422403/5237903/d6e66d5e-78a4-11e4-84b4-17acf2099cde.png)

Et c'est dans le `execute(buffer)` qu'on ajouterait les actions dans l'historique du buffer passé en paramètre ? Genre : 

``` scala
// Insertion class

def execute(buffer: Buffer): Unit = {
  buffer.history.add(this)
  buffer.simpleInsert(...)
}
```

Ça me paraît bien et si je me trompe pas, il y a le pattern Command à priori, en plus du Composite.

Après le seul défaut que je vois par rapport à cette histoire de macro d'action _(qui de mon point de vue n'a aucun intérêt, mais bon, c'est dans le sujet :smile:)_, c'est qu'il faudrait vérifier si toutes les actions sont possibles pour le buffer donné. Car si on demande d'insérer par exemple "Chaise" à la position 23 et que le buffer a une taille de 10, ça va planter. Du coup l'exécution de macro devra être controllé par `Editor`.

**Comment by Matthieu-Riou** [comment]
Yep pour le diagramme ! Mais avec aussi d'autres actions comme Copier, Coller (qui serait déjà elle même des macros en soit).

Mais pour l'historique c'est pas ça justement. Ça serait plus : 

``` scala
// Insertion class

def execute(buffer: Buffer): Unit = {
  buffer.history.add(new HistoryInsertion(buffer, this.text, this.index))
  buffer.simpleInsert(...)
}
```

**Comment by Cowa** [comment]
Done #20
